#!/bin/bash

if [[ "$EUID" -ne 0 ]]; then
echo ""
echo "กรุณาเข้าสู่ระบบผู้ใช้ root ก่อนทำการใช้งานสคริปท์"
echo "คำสั่งเข้าสู่ระบบผู้ใช้ root คือ sudo -i"
echo ""
exit
fi

if [[ ! -e /dev/net/tun ]]; then
echo ""
echo "TUN ไม่สามารถใช้งานได้"
exit
fi

# Set Localtime GMT +7
ln -fs /usr/share/zoneinfo/Asia/Bangkok /etc/localtime

clear
# IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)
# if [[ "$IP" = "" ]]; then
IP=$(wget -4qO- "http://whatismyip.akamai.com/")
# fi

if [[ -e /etc/debian_version ]]; then
OS=debian
VERSION_ID=$(cat /etc/os-release | grep "VERSION_ID")
GROUPNAME=nogroup
RCLOCAL='/etc/rc.local'

if [[ "$VERSION_ID" != 'VERSION_ID="7"' ]] && [[ "$VERSION_ID" != 'VERSION_ID="8"' ]] && [[ "$VERSION_ID" != 'VERSION_ID="9"' ]] && [[ "$VERSION_ID" != 'VERSION_ID="14.04"' ]] && [[ "$VERSION_ID" != 'VERSION_ID="16.04"' ]] && [[ "$VERSION_ID" != 'VERSION_ID="17.04"' ]]; then
echo ""
echo "🇹🇭นายแมนจัง🇹🇭"
echo ""
echo "เวอร์ชั่น OS ของคุณเป็นเวอร์ชั่นที่ยังไม่รองรับ"
echo "สำหรับเวอร์ชั่นที่รองรับได้ จะมีดังนี้..."
echo ""
echo "Ubuntu 14.04 - 16.04 - 17.04"
echo "Debian 7 - 8 - 9"
echo ""
exit
fi
else
echo ""
echo "🇹🇭นายแมนจัง🇹🇭"
echo ""
echo "OS ที่คุณใช้ไม่สามารถรองรับได้กับสคริปท์นี้"
echo "สำหรับ OS ที่รองรับได้ จะมีดังนี้..."
echo ""
echo "Ubuntu 14.04 - 16.04 - 17.04"
echo "Debian 7 - 8 - 9"
echo ""
exit
fi

# Color
GRAY='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

# Menu
echo ""
echo "🇹🇭นายแมนจัง🇹🇭"
echo ""
if [[ -e /usr/local/bin/Check-Thai ]]; then
echo -e "ฟังก์ชั่นสคริปท์ ${GRAY} 🇹🇭นายแมนจัง🇹🇭${NC}"
echo ""
if [[ -e /etc/openvpn/server.conf ]]; then
echo -e "|${GRAY} 1${NC}| ถอนการติดตั้ง OPENVPN ที่ควบคุมการใช้งานผ่านเทอร์มินอล😁 ${GREEN} ✔   ${NC}"
else
echo -e "|${GRAY} 1${NC}| ติดตั้ง OPENVPN ที่ควบคุมการใช้งานผ่านเทอร์มินอล😁 ${GREEN} ✔   ${NC}"
fi
echo -e "|${GRAY} 2${NC}| ติดตั้ง OPENVPN ที่ควบคุมการใช้งานผ่าน PRITUNL😁 ${GREEN} ✔   ${NC}"
echo -e "|${GRAY} 3${NC}| ติดตั้ง SSH DROPBEAR😁 ${GREEN} ✔   ${NC}"
echo -e "|${GRAY} 4${NC}| ติดตั้ง WEB PANEL😏 ${GRAY} ✖   ${NC}"
if [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
if [[ ! -e /etc/squid3/squid.conf ]]; then
echo -e "|${GRAY} 5${NC}| ติดตั้ง SQUID PROXY😋 ${GREEN} ✔   ${NC}"
elif [[ -e /etc/squid3/squid.conf ]]; then
echo -e "|${GRAY} 5${NC}| ถอนการติดตั้ง SQUID PROXY🙄 ${GREEN} ✔   ${NC}"
fi

elif [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="17.04"' ]]; then
if [[ ! -e /etc/squid/squid.conf ]]; then
echo -e "|${GRAY} 5${NC}| ติดตั้ง SQUID PROXY😜 ${GREEN} ✔   ${NC}"
elif [[ -e /etc/squid/squid.conf ]]; then
echo -e "|${GRAY} 5${NC}| ถอนการติดตั้ง SQUID PROXY😭 ${GREEN} ✔   ${NC}"
fi
fi
echo ""
echo -e "|${GRAY} 0${NC}| 🤑อัพเดตฟังก์ชั่นสคริปท์"
echo -e "|${GRAY}00${NC}| 😧เปลี่ยนเป็นภาษาอังกฤษ"
echo ""
echo ""
read -p "เลือกหัวข้อที่ต้องการใช้งาน : " FUNCTIONSCRIPT

elif [[ ! -e /usr/local/bin/Check-Thai ]]; then
echo -e "สคริป ${GRAY}นายแมนจัง${NC}"
echo ""
if [[ -e /etc/openvpn/server.conf ]]; then
echo -e "|${GRAY} 1${NC}| REMOVE OPENVPN TERMINAL CONTROL ${GREEN} ✔   ${NC}"
else
echo -e "|${GRAY} 1${NC}| INSTALL OPENVPN TERMINAL CONTROL ${GREEN} ✔   ${NC}"
fi
echo -e "|${GRAY} 2${NC}| INSTALL OPENVPN PRITUNL CONTROL ${GREEN} ✔   ${NC}"
echo -e "|${GRAY} 3${NC}| INSTALL SSH DROPBEAR ${GREEN} ✔   ${NC}"
echo -e "|${GRAY} 4${NC}| INSTALL WEB PANEL ${GRAY} ✖   ${NC}"
if [[ "$VERSION_ID" = 'VERSION_ID="7"' || "$VERSION_ID" = 'VERSION_ID="8"' || "$VERSION_ID" = 'VERSION_ID="14.04"' ]]; then
if [[ ! -e /etc/squid3/squid.conf ]]; then
echo -e "|${GRAY} 5${NC}| INSTALL SQUID PROXY ${GREEN} ✔   ${NC}"
elif [[ -e /etc/squid3/squid.conf ]]; then
echo -e "|${GRAY} 5${NC}| REMOVE SQUID PROXY ${GREEN} ✔   ${NC}"
fi

elif [[ "$VERSION_ID" = 'VERSION_ID="9"' || "$VERSION_ID" = 'VERSION_ID="16.04"' || "$VERSION_ID" = 'VERSION_ID="17.04"' ]]; then
if [[ ! -e /etc/squid/squid.conf ]]; then
echo -e "|${GRAY} 5${NC}| INSTALL SQUID PROXY ${GREEN} ✔   ${NC}"
elif [[ -e /etc/squid/squid.conf ]]; then
echo -e "|${GRAY} 5${NC}| REMOVE SQUID PROXY ${GREEN} ✔   ${NC}"
fi
fi
echo ""
echo -e "|${GRAY} 0${NC}| UPDATE FUNCTION SCRIPT"
echo -e "|${GRAY}00${NC}| เปลี่ยนเป็นภาษาไทย"
echo ""
echo ""
read -p "Select a Function Script : " FUNCTIONSCRIPT
fi

case $FUNCTIONSCRIPT in

1) # ==================================================================================================================

newclient () {
cp /etc/openvpn/client-common.txt ~/$1.ovpn
echo "<ca>" >> ~/$1.ovpn
cat /etc/openvpn/easy-rsa/pki/ca.crt >> ~/$1.ovpn
echo "</ca>" >> ~/$1.ovpn
echo "<cert>" >> ~/$1.ovpn
cat /etc/openvpn/easy-rsa/pki/issued/$1.crt >> ~/$1.ovpn
echo "</cert>" >> ~/$1.ovpn
echo "<key>" >> ~/$1.ovpn
cat /etc/openvpn/easy-rsa/pki/private/$1.key >> ~/$1.ovpn
echo "</key>" >> ~/$1.ovpn
echo "<tls-auth>" >> ~/$1.ovpn
cat /etc/openvpn/ta.key >> ~/$1.ovpn
echo "</tls-auth>" >> ~/$1.ovpn
}

if [[ -e /etc/openvpn/server.conf ]]; then
echo ""
read -p "ต้องการถอนการติดตั้ง OpenVPN หรือไม่  (Y or N): " -e -i N REMOVE

if [[ "$REMOVE" = 'Y' ]]; then
PORT=$(grep '^port ' /etc/openvpn/server.conf | cut -d " " -f 2)
PROTOCOL=$(grep '^proto ' /etc/openvpn/server.conf | cut -d " " -f 2)
if pgrep firewalld; then
IP=$(firewall-cmd --direct --get-rules ipv4 nat POSTROUTING | grep '\-s 10.8.0.0/24 '"'"'!'"'"' -d 10.8.0.0/24 -j SNAT --to ' | cut -d " " -f 10)
firewall-cmd --zone=public --remove-port=$PORT/$PROTOCOL
firewall-cmd --zone=trusted --remove-source=10.8.0.0/24
firewall-cmd --permanent --zone=public --remove-port=$PORT/$PROTOCOL
firewall-cmd --permanent --zone=trusted --remove-source=10.8.0.0/24
firewall-cmd --direct --remove-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP
firewall-cmd --permanent --direct --remove-rule ipv4 nat POSTROUTING 0 -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP
else
IP=$(grep 'iptables -t nat -A POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to ' $RCLOCAL | cut -d " " -f 14)
iptables -t nat -D POSTROUTING -s 10.8.0.0/24 ! -d 10.8.0.0/24 -j SNAT --to $IP
sed -i '/iptables -t nat -A POSTROUTING -s 10.8.0.0\/24 ! -d 10.8.0.0\/24 -j SNAT --to /d' $RCLOCAL
if iptables -L -n | grep -qE '^ACCEPT'; then
iptables -D INPUT -p $PROTOCOL --dport $PORT -j ACCEPT
iptables -D FORWARD -s 10.8.0.0/24 -j ACCEPT
iptables -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT
sed -i "/iptables -I INPUT -p $PROTOCOL --dport $PORT -j ACCEPT/d" $RCLOCAL
sed -i "/iptables -I FORWARD -s 10.8.0.0\/24 -j ACCEPT/d" $RCLOCAL
sed -i "/iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT/d" $RCLOCAL
fi
fi
if hash sestatus 2>/dev/null; then
if sestatus | grep "Current mode" | grep -qs "enforcing"; then
if [[ "$PORT" != '1194' || "$PROTOCOL" = 'tcp' ]]; then
semanage port -d -t openvpn_port_t -p $PROTOCOL $PORT
fi
fi
fi
apt-get remove --purge -y openvpn
apt-get remove --purge -y nginx
rm -rf /home/vps/public_html
rm -rf /etc/openvpn
rm -rf /usr/local/bin/*
echo ""
read -p "ต้องการลบข้อมูลบัญชีทั้งหมดหรือไม่ (Y or N) : " -e -i N DELETEACCOUNT
if [[ "$DELETEACCOUNT" = "Y" ]]; then
UIDN=1000
while read CHECKCLIENT
do
ACCOUNT="$(echo $CHECKCLIENT | cut -d: -f1)"
ID="$(echo $CHECKCLIENT | grep -v nobody | cut -d: -f3)"
if [[ $ID -ge $UIDN ]]; then
userdel $ACCOUNT
fi
done < /etc/passwd
fi
echo ""
echo -e "${GRAY}OpenVPN Removed. ${NC} "
echo ""
exit
else
echo ""
echo -e "${GRAY}Removal Aborted. ${NC} "
echo ""
exit
fi
exit

# elif [[ -e /etc/apt/sources.list.d/pritunl.list ]]; then
# echo ""
